### ISSUE TITLE
"Handshake failed due to invalid Upgrade header: null" on enabling SSL

### ISSUE THREAD

**Issue by dozingpip** [Lurkars/ghs-server#1]
Using openjdk-18.0.2_windows-x64_bin - jdk-18.0.2
Trying and failing to enable SSL.
Upon loading https://localhost:8080/ , my server bash terminal says `Handshake failed due to invalid Upgrade header: null` , and the localhost page says `Can "Upgrade" only to "WebSocket".`.
pastebin of my whole log from bash running the server jar: https://pastebin.com/ZxPLwQcy

**Comment by Lurkars** [comment]
This is correct behavior. You are trying to access the server in the browser, but it is used for communication with GHS client, so you should just not access https://localhost:8080/. Instead, in GHS client you set server connection with:
```
Url: localhost
Port: 8080
Secure: true (checked)
```

A different topic is, if you want to serve the client itself. If you setup that correctly, than you need to enter directly the client url which is https://localhost:8080/index.html in your case. Note: if you serving GHS with the server for usage in local network, there is no need for using SSL.

Please close, if this solved your issue.

**Comment by dozingpip** [comment]
Uh, hm, if I do that in the client, when I hit accept when Secure is enabled, it opens a separate gloomhaven secretary window, nothing in the dev console for this window and nothing happens when I force reload... I am testing it on a local network currently, but will be using it with people outside my local network later.

**Comment by Lurkars** [comment]
Okay, maybe this is just bad UX. But the accept button appears, when you "possibly" need to accept the self-signed certificate. Did you tried to just click "Connect" anyways? Please try, if connection that works.

**Comment by dozingpip** [comment]
I hit Connect and it says "No Connection" and then the text changes to "Closed".

**Comment by dozingpip** [comment]
Is there a router setting that needs to be enabled or something? Pretty sure UPnP is enabled, not sure else I would even need.

**Comment by Lurkars** [comment]
I am still unsure about your setup. If you're only testing locally now, there should not be any firewall or router issues. Did you add an exception in your browser for the self-signed certificate? I am not sure, if you rejected it first, how you can re-show the dialog. So maybe that's just the issue. Are you using latest client with latest server? Have you tried local first without SSL and it worked?

**Comment by dozingpip** [comment]
I am using the latest client with latest server, and it does work local without SSL. Actually, huh ok then, I just got it to work in the browser, but it still doesn't work with the same input in the desktop client version? Maybe since the acceptance window is like that?

**Comment by Lurkars** [comment]
Ah okay, I see, The issue is with the desktop (electron) client. I may think of ways, to accept a self signed certificate, because the embedded chromium does not have a dialog to accept it. Anyways I tested connection with electron app to an insecure server without SSL and it worked. So we don't have the problem of a forced SSL connection.

So the only issue I really see here is, if you want to use the same self-hosted server for an electron client and for a hosted web client on HTTPS. The one requires SSL (https client), the other not (electron). So solution may be to add support to run secure and insecure server at once on different ports. I will take a look at this.

**Comment by Lurkars** [comment]
This was added in [v0.9.18](https://github.com/Lurkars/ghs-server/releases/tag/v0.9.18), when running with SSL, a HTTP server will be run on port 8081 (can be changed with `server.http.port` property in `application.proprties`).
