### ISSUE TITLE
Regular Disconnects (self hosted and your server, android & iphone)

### ISSUE THREAD

**Issue by PyroghostX** [Lurkars/ghs-server#11]
We played again last friday and still got regular disconnects.

On android it would be randomly when having the app open
meaning, anytime we would leave the app or the phone would go to sleep, opening the app or waking the phone it would always reconnect/connect just fine
but randomly when just leaving the screen on for a long time the app would randomly disconnect (connection icons go red up on the top left)

On iphone - she would just get way more often disconnects than us android users

Have you thought of any logging that could be done so I can help you solve the issue?

We love GHS, love that it does all the attack decks, it does so much more than xhaven, so we want to keep using it. And I want to help solve the disconnect issues

**Comment by Lurkars** [comment]
I will think about adding some kind of logging that everyone can easily access to be able to send to me. In the meantime, if the icon is red, just click on it and it should reconnect. So maybe not the best user experience but a workaround by now. In general I have plans to refactor the server a bit, maybe this will solves issues too.

**Comment by earlofrose** [comment]
This happened to us. After digging around, we found that cloudflare had a 60 second timeout on websocket connections. Turned off the proxy at cloudflare and it started working without disconnects.

**Comment by AcidWeb** [comment]
I use nginx for SSL termination and I also had to bump timeouts to get it running.

Additionally reconnect process was disabling the "Secure" option and entire process failing as it was trying to connect unencrypted WS.

**Comment by PyroghostX** [comment]
> This happened to us. After digging around, we found that cloudflare had a 60 second timeout on websocket connections. Turned off the proxy at cloudflare and it started working without disconnects.

This did it! Thank you! Marking this issue as closed
