### ISSUE TITLE
Cloud based hosting IAC options?

### ISSUE THREAD

**Issue by Greven145** [Lurkars/ghs-server#15]
I have a pulumi stack that deploys the server, ui, and a caddy instance to Azure, and thought an easy way for people to set up self hosting would be useful. I can submit a PR, not sure if that would be desired or a different repo would be better maybe.

**Comment by Lurkars** [comment]
What would this PR include? I already struggled creating docker support :sweat-smile:. 
In the end it's just a Java application and one can think of thousands ways to deploy it and anyone wants to run this on a server should have knowledge to perform setup to it's needs. So why provide azure+caddy? Why not aws+nginx? Apache on oracle freetier? I hope you understand my point. So please provide some more details for a better decision.

**Comment by Greven145** [comment]
Oh, definitely can provide lots of options, this is just the one that I already have. DevOps is my day job, so creating lots of alternatives would be absolutely doable. I'll put together a few options that I think people might like and start it in a separate repo to provide details about what I mean.

If most people would want to roll their own, then yeah, this is a moot point, but I personally spent a few hours creating the version I use for my own self hosting and thought others might benefit from it.

**Comment by Lurkars** [comment]
My question was more rhetorical, sorry. I just don't think, there is that one way to deploy so it's easy and most importantly recommended for inexperienced users to use. I more think, I don't want to recommend hosting this, if you're not a bit experienced in what you do. And if you are, you should not need several guides on how to deploy with different combinations of tools/proxies etc. So I provide a general guide on how the server is run, and even provide docker images/compose files. From my POV this should be enough. If you have a nice setup and like to share it, I will think about linking this in the README, but I am still unsure if I want to provide more running scripts/config than already there.

**Comment by rsmayda** [comment]
@Greven145 I would be interested in this! Could you throw this code in a public fork?

**Comment by Greven145** [comment]
@rsmayda For sure, I have it in a private repo right now, let me make sure I'm not exposing anything heinous and I'll link it here in a day or so.

**Comment by Greven145** [comment]
@rsmayda Apologies on the delay:

https://github.com/Greven145/ghs-pulumi
