### ISSUE TITLE
Public server not working with latest release of gloomhavensecretary

### ISSUE THREAD

**Issue by TylerHelmuth** [Lurkars/ghs-server#2]
I appears that after the 0.9.16 release of gloomhavensecretary the server returns an error when trying to connect with it.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/12352919/180849031-f1303c66-bf24-4679-ad4d-ff373af3f444.png">

I also get this error locally when using latest GHS serving an older version of gloomhavensecretary.

**Comment by Lurkars** [comment]
Can you describe your setup in more detail? So you are using a selfhosted GHS and connect to the public server? When running GHS locally and connecting to the server, everything is fine for me.
![image](https://user-images.githubusercontent.com/2760570/180854746-4384208c-cf9b-4193-a153-e2e4ee996336.png)

For now, this stuff is still in development, so there may be version changes, that does not work with updating only one component. So if you're using both selfhostest, server and client please always use latest versions for both.

**Comment by TylerHelmuth** [comment]
I got local working again by updating to the latest version.

I have not been able to successfully connect an instance of `https://ghs.champonthis.de/index.html` to `152.70.60.220` on port `8080`. 

<img width="405" alt="Screen Shot 2022-07-25 at 1 17 29 PM" src="https://user-images.githubusercontent.com/12352919/180857041-f3bebd98-4f2b-48ce-81d3-f404df880ff4.png">

But I was able to connect to `ghs.champonthis.de/server` on port `443`.

**Comment by Lurkars** [comment]
If you're trying to connect from a HTTPS client (https://ghs.champonthis.de) almost any browser will upgrade the server connection to SSL and therefor the server will reject it. That's why I added the SSL proxy under ghs.champonthis.de/server. So if this was the issue, then I close this.
