### ISSUE TITLE
Crossover Character Sheets

### ISSUE THREAD

**Issue by obstel** [Lurkars/ghs-server#25]
Hi Lukars,

Fisr of all great work on the app, we are using it quite a lot and it helps so much in resolving the managing all tokens.

We are using gloomhaven characters and the app is working fine with the frosthaven campaign, however the charactersheets are not the updated version for crossover characters.

Would you mind to add those cheets including the masteries?

And a conversion for the existing characters, otherwise we would loose all progress.

Kind regards
Christian

**Comment by Lurkars** [comment]
Just go in client to data management cand enable "Frosthaven Crossover Characters".
