### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by eXitus132** [Lurkars/ghs-server#29]
Hi everyone,

yesterday i opened up a server with the latest release and all clients couldnt connect to it. We did that in the local area and with https approach (worked fine until latest release). Any suggestions? Thanks and best regards, Eric

**Comment by Lurkars** [comment]
I cannot reproduce. For me everything is working as before. You may need to re-accept the self-signed certificate? Just open server url in browser to check this. Is this is not the case, then please provide some more details about your setup.

**Comment by eXitus132** [comment]
Thanks for your response, here are more details:
I got a new laptop and copied everything from the .ghs folder there. I installed the latest java version and downloaded your latest server application. I ran it and everything seems fine (got an ip adress, https is also enabled and my latest save file was shown there). When i try to connect with a client i got after a while the message unable to connect (took to long). Before of that i always got the message insecure but you could continue by ignore and than it worked. Any things that come up?

**Comment by Lurkars** [comment]
Can you please open the server URL in the browser used for GHS and add an exception for the self-signed cert.

**Comment by eXitus132** [comment]
That didnt work but i got it - it was the firewall. i just disabled it and then it worked (couldnt ping that laptop in the network as well thats were i found the trace^^). Thanks for your help Lurkars!
