### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by illotum** [Lurkars/ghs-server#3]
Hello, I built and published a simple Docker wrapper around your server. While that's more that satisfactory for my own needs, I wonder if it wasn't better to promote an authoritative container from the maintainer (you). Feel free to poach my config!

**Comment by Lurkars** [comment]
Thank you very much. I added a first version of a Dockerfile now. Need to go more into the docker hub stuff and so on how would best to provide a build image.

**Comment by illotum** [comment]
I realized I never linked it, here you go https://github.com/illotum/docker-ghs-server

**Comment by Lurkars** [comment]
Just short update, that I was just very busy with clients GHS and didn't come to take a deeper look. But all open issues are of course on my agenda.

**Comment by illotum** [comment]
Marginally related -- and I don't know where your interests lie -- but I can take over the server side if you'd like.

I'm definitely not a front end dev, but server side is my day job. We just need to properly define the API.

**Comment by jgwehr** [comment]
Looking forward to the progress you both can make! I just started trying this out. My compose file is below if it's at all helpful. I _am_ getting a whole bunch of delay and, with just 2 local clients subscribed, the server steadily increases its RAM consumption.
If I can be helpful with testing, etc do let me know!
https://github.com/jgwehr/homelab-docker/blob/feature/gloomhaven-secretary/extra-services/gloomhaven-secretary/docker-compose.yml

**Comment by Lurkars** [comment]
> Marginally related -- and I don't know where your interests lie -- but I can take over the server side if you'd like.
> 
> I'm definitely not a front end dev, but server side is my day job. We just need to properly define the API.

Hey thanks. I am also more backend developer 😅 For now all this works fine. Of course I am always happy about contribution, but most logic lies in the client (and should, I am also thinking about adding P2P support over WebRTC to client to be able to omit the external server component). So for now the server only consist about validating game model (by mapping JSON to properly classes), store then JSON in DB and send state to all connected clients. So as long as this architecture stays, I don't think there is much to develop here. But yes I am happy about docker support. I have basic knowledge to be able to create Dockerfiles and compose files, but this docker hub stuff is complete new to me. So happy about contributions here.

**Comment by Lurkars** [comment]
> Looking forward to the progress you both can make! I just started trying this out. My compose file is below if it's at all helpful. I _am_ getting a whole bunch of delay and, with just 2 local clients subscribed, the server steadily increases its RAM consumption. If I can be helpful with testing, etc do let me know! https://github.com/jgwehr/homelab-docker/blob/feature/gloomhaven-secretary/extra-services/gloomhaven-secretary/docker-compose.yml

Hey maybe create an extra issue for this. I haven't tried your docker-compose.yml yet, but in general my local server stays at 30-50 MB(!) of ram, so usage is pretty pretty low. So I am really wondering, what's going on at your setup. I will add a monitoring profile to include Javamelody, so maybe this can help investigating the issue.

**Comment by jgwehr** [comment]
Will do after work; when I can get some clear logs and other details for you!

**Comment by illotum** [comment]
I just discovered you can now host containers right by the repo, maybe that will be more convenient. http://ghcr.io/

**Comment by jgwehr** [comment]
Interesting - I wonder if it prebuilds the image? I'll try it out tonight!

I created this shell script (mostly to learn how) to publish to hub.docker because the builds took quite a bit of time. Happily deprecated if ghcro handles it. https://github.com/jgwehr/homelab-docker/blob/37c4f2cc76da5e143ed1e7bbbd4f81f89d6842ca/extra-services/gloomhaven-secretary/image-builder.sh

**Comment by Lurkars** [comment]
I don't think that I would like to invoice a third party tool for docker hub support. But @jgwehr your script looks like a good start for using GitHub actions to publish those images to hub. With quick research, I found something like this
https://faun.pub/how-to-push-docker-image-using-github-actions-694397c4f557
I may just try this out, but now very busy with Frosthaven data. If someone here wants to try this beforehand, I really appreciate.

**Comment by jgwehr** [comment]
@Lurkars As a know-nothing, I'm pretty proud of myself, haha!

I'm very close, just need to work on getting the right image **tags** to publish. I will assume you'd want `:latest` and `:v*` upon commits to `main`. When I get it worked out I'll submit a PR for you.

- current workflow: https://github.com/jgwehr/ghs-server/blob/docker/push-workflow/.github/workflows/publish-docker-image.yml
- executed Github Action on PULL: https://github.com/jgwehr/ghs-server/actions/runs/3475481920/jobs/5809756882
- automated push to hub.docker.com: https://hub.docker.com/layers/snoopeppers/gloomhaven-secretary-server/docker-push-workflow/images/sha256-13fcd1edb58a43b171a0188c46384558be276431644a22844fca85121dbda761?context=repo
- automated push to ghcr.io: https://github.com/jgwehr/ghs-server/pkgs/container/gloomhaven-secretary-server

**Comment by jgwehr** [comment]
Two options submitted as PRs. Depending on which you prefer, doing the same for the client app should be pretty quick.

**Comment by Lurkars** [comment]
> Two options submitted as PRs. Depending on which you prefer, doing the same for the client app should be pretty quick.

Just took a quick look, but do I understand it right, that the only difference is, that one creates a separate workflow and other integrates in existing? But logic what happens is complete same? If so, it's easy pick for the separate file! Will merge and test later today! Thank you very much! (I already registered docker account free days ago)
