### ISSUE TITLE
[Docker] Server performance, memory utilization

### ISSUE THREAD

**Issue by jgwehr** [Lurkars/ghs-server#4]
Hi there, I recently started exploring the Docker versions of both the server and client.

I've had a few memory issues with the server. Some observations below.

Settings for all scenarios:
- `connect automatically` = true
- `synchronize settings` = true
- `secure` = false

### Server only (no clients)
Server `MEM USAGE` starts off, and stabilizes around 190MiB

### Server + 1 Client
Server `MEM USAGE` stable around 190MiB

- Change state of `Elements`: around ~1.5MiB gain. Stable
- Reveal, Shuffle, add Bless/Curse/-1 to `Monster Modifer Deck`: minor increase. Stable.
- Add `Character` (Brute): Stable
- Set `Scenario` (GH01): Stable

### Server + 2 Clients
Upon opening a new browser/client: Server `MEM USAGE` increase to ~250 MiB. 
Steadily afterwards, gains about 1MiB per "tick". There doesn't seem to be a cap... at time of submitting, ~355 MiB

- new Client is subscribed in the same browser (FireFox) on the same device (Win10)
- no interaction other than opening the session

### Server + dropping 1 client, total = 1
Upon dropping 1 client: Server `MEM USAGE` stablizes.

_Originally posted by @jgwehr in https://github.com/Lurkars/ghs-server/issues/3#issuecomment-1308045217_

**Comment by jgwehr** [comment]
Here's the docker logs from the steps above. If there's a way to get a more verbose log, let me know!

[gloomhaven-server-2022-11-09T15-41-15.log](https://github.com/Lurkars/ghs-server/files/9972621/gloomhaven-server-2022-11-09T15-41-15.log)

**Comment by Lurkars** [comment]
So I just tested your docker-compose.yml
With 512 MB Ram to server, I had a usage of 144 MB went up to 148 after some time of usage. Then I restarted with 128 MB Ram, raised after time of usage and also adding a third client from 108 MB to 110 MB. So this is full usage of container and not application itself. But please remember the Java memory management. The garbage collection is not just always triggered, so as long as the application has RAM available, it may increase. Also I had connected 2 clients via localhost and one via internal network. No problems. 

Now I read again details of your post and saw that you have "synchronize settings = true", so I tested that and performance dropped hard. Clients hang up etc. So I think there is a big issues with sync settings. I will investigate!

**Comment by Lurkars** [comment]
I fixed this with [v0.24.4](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.24.4)

I also released a new server version [v0.24.4](https://github.com/Lurkars/ghs-server/releases/tag/v0.24.4) with some small improvements but this should not relate to this issue. So please retest your setup with a client in version v0.24.4!

**Comment by jgwehr** [comment]
Initially testing (I'm doing this between meetings :) ) is... **very good!**.
0/1/2 client scenarios are all stable and very snappy. ~117MiB

Since these image take a while to build, I took the liberty of publishing for others' convenience. I'll happily take them down or share the short script I made to do it.

https://hub.docker.com/repository/docker/snoopeppers/gloomhaven-secretary
https://hub.docker.com/repository/docker/snoopeppers/gloomhaven-secretary-server

**Comment by jgwehr** [comment]
Okay, I've had the container up for about an hour and half. One client connected the whole time and a few joining sporadically from different devices.
Has varied between 117 and 131 MiB. I think you've done it! 

My next goal is to get it running behind a reverse proxy and SSL. If I can get it done (which honestly, should be easy), I'll post my work if you'd like.

**Comment by Lurkars** [comment]
I have no big nginx experience, but already used apache2 as reverse proxy for GHS and want to mention that you need add Rewrite Rules for Websocket upgrading.

```
RewriteEngine on
RewriteCond ${HTTP:Connection} upgrade [NC]
RewriteCond ${HTTP:Upgrade} websocket [NC]
RewriteRule /.* "ws://localhost:8080/$1" [P,L]
```

**Comment by jgwehr** [comment]
>you need add Rewrite Rules for Websocket upgrading.

Cool, thanks! I was able to get it up and running very quickly with Caddy. With some a few weird client-server scenario exceptions. I'll explore this bit to see if it solves things!

Can you explain the expected behavior if websockets are **not upgraded**? I was able to connect to the server remotely from **my hosted client** but not from gloomhaven-secretary.de. Caddy tends to take care of a lot of things so I'm wondering if websockets are already tackled but there's some other issue.

**Comment by Lurkars** [comment]
> I was able to connect to the server remotely from **my hosted client** but not from gloomhaven-secretary.de. Caddy tends to take care of a lot of things so I'm wondering if websockets are already tackled but there's some other issue.

Did your server uses already SSL? Otherwise every browser will reject connection from a TLS (gloomhaven-secretary.de) to insecure connection (your local server).

**Comment by jgwehr** [comment]
Yep! Both my hosted client and server are SSL. I can send you a private message with the URLs if you're at all curious - but I'm trying not to waste your time if this isn't helpful for the app itself 😃 

From gloomhaven-secretary.de I get an "Accept?" prompt to the (my hosted) app which redirects to `/noclient.html`

**Comment by Lurkars** [comment]
> I can send you a private message with the URLs

Yes, you can ping me at lurkars@gloomhaven-secretary.de
