### ISSUE TITLE
Code cleanup ?

### ISSUE THREAD

**Issue by FlavianIuga** [Lurkars/ghs-server#8]
Can I offer to do some code clean-up ? Nothing that will change any behaviour: try-with-resorces blocks, diamond operators, return types, etc..

I'm new to contributing to github projects. Been playing Gloomhaven since 2020, really like the game :)

**Comment by Lurkars** [comment]
Of course, just summit a PR and I can take a look 👍

**Comment by FlavianIuga** [comment]
#9 PR done. If you want, open issues for things that need implementation. I can't promise anything but maybe I will take a look. I know the game well enough by now, maybe played 60-70 scenarios.
